# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_install:
      - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      - unzip awscliv2.zip
      - ./aws/dist/aws codeartifact login --tool pip --repository python-ds --domain ledger-data-science --domain-owner 054739135172 --region us-east-2
	post_create_environment:
	  - python3.11 -m pip install poetry
	post_install:
	  - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH poetry install --with docs


mkdocs:
  configuration: mkdocs.yml
