site_name: BayesBlend
site_url: https://ledger.bayesblend.com/

theme: 
  name: material
  palette: 
    scheme: default
    primary: indigo
  features:
    - content.code.copy


nav:
  - Home: index.md
  - Installation: user-guide/installation.md
  - Contributing: developer-guide/contributing.md
  - User Guide: user-guide/
  - Developer Guide: developer-guide/

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
