name: bayesblend python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: pipx install poetry
      - name: Install and cache dependencies
        run: |
          poetry env use "3.11"
          poetry install
      - name: cmdstan env vars
        run: |
          echo "CMDSTAN_PATH=${HOME}/.cmdstan" >> $GITHUB_ENV
          echo "CMDSTAN_VERSION=2.33.1" >> $GITHUB_ENV
        shell: bash
      - name: Cache cmdstan
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CMDSTAN_PATH }}
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}
          restore-keys: ${{ runner.os }}-cmdstan-
      - name: Install cmdstan
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry run python -m cmdstanpy.install_cmdstan -v ${{ env.CMDSTAN_VERSION }} --progress
      - name: Test
        run: poetry run pytest

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install poetry
      run: pipx install poetry
    - name: Install and cache dependencies
      run: |
          poetry env use "3.11"
          poetry install 
    - name: Get Python changed files
      id: changed-py-files
      uses: tj-actions/changed-files@v44
      with:
        files: |
          *.py
          **/*.py
    - name: Run if any .py files changed
      if: steps.changed-py-files.outputs.any_changed == 'true'
      run: poetry run mypy ${{ steps.changed-py-files.outputs.all_changed_files }} --ignore-missing-imports

