name: BayesBlend python application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  meta:
    runs-on: ubuntu-latest
    outputs: 
      any-changed: ${{ steps.changed-py-files.outputs.any_changed }}
      all-changed-files: ${{ steps.changed-py-files.outputs.all_changed_files }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get Python changed files
        id: changed-py-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            *.py
            **/*.py
          files_ignore: |
            test/**
  mypy:
    needs: meta
    runs-on: ubuntu-latest
    if: ${{ needs.meta.outputs.any-changed == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install poetry
      run: pipx install poetry
    - name: Install dependencies
      run: |
          poetry env use "3.11"
          poetry install 
    - name: Run mypy check
      run: poetry run mypy ${{ needs.meta.outputs.all-changed-files }} --ignore-missing-imports
          
  ruff:
    needs: meta
    runs-on: ubuntu-latest
    if: ${{ needs.meta.outputs.any-changed == 'true' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: |
            poetry env use "3.11"
            poetry install 
      - name: Run ruff check
        run: poetry run ruff check ${{ needs.meta.outputs.all-changed-files }}

  tests:
    needs: [meta, mypy, ruff]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install poetry
        run: pipx install poetry
      - name: Install dependencies
        run: |
          poetry env use "3.11"
          poetry install
      - name: cmdstan env vars
        run: |
          echo "CMDSTAN_PATH=${HOME}/.cmdstan" >> $GITHUB_ENV
          echo "CMDSTAN_VERSION=2.33.1" >> $GITHUB_ENV
        shell: bash
      - name: Cache cmdstan
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ env.CMDSTAN_PATH }}
          key: ${{ runner.os }}-cmdstan-${{ env.CMDSTAN_VERSION }}
          restore-keys: ${{ runner.os }}-cmdstan-
      - name: Install cmdstan
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          poetry run python -m cmdstanpy.install_cmdstan -v ${{ env.CMDSTAN_VERSION }} --progress
      - name: Run tests
        run: poetry run pytest

  release:
    needs: [tests, mypy, ruff]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' && !contains(github.event.head_commit.message, 'chore(release):')
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Semantic Release
        run: |
          pip install python-semantic-release
          git config user.name github-actions
          git config user.email github-actions
          semantic-release publish
      
    